language: c

os:
  - linux
  - osx

before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq update; fi

install:
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew cask uninstall oclint; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew install fftw; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew install gsl; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install -y libfftw3-dev libgsl0-dev; fi

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - make install
    - ctest -vv
